version: "3.8"

services:
  postgres-beautique:
    image: postgres:17
    hostname: postgres-beautique
    environment:
      POSTGRES_DB: beautique
      POSTGRES_USER: beautique
      POSTGRES_PASSWORD: beautique
    volumes:
      - "D:/db-beautique:/var/lib/postgresql/data"
      - "./init-beautique-schema.sql:/docker-entrypoint-initdb.d/init-beautique-schema.sql"
    ports:
      - "3334:5432"
    networks:
      - beautique-network

  rabbitmq:
      image: "rabbitmq:3-management"
      hostname: rabbitmq
      environment:
        RABBITMQ_DEFAULT_USER: user
        RABBITMQ_DEFAULT_PASS: password
      ports:
        - "5673:5672"   # AMQP na porta 5673
        - "15673:15672" # Painel na porta 15673
      networks:
        - beautique-network
      volumes:
        - rabbitmq-data:/var/lib/rabbitmq
        - rabbitmq-log:/var/log/rabbitmq

networks:
  beautique-network:
    driver: bridge

# Aqui dizemos para o Docker gerenciar essas pastas internamente
volumes:
  rabbitmq-data:
  rabbitmq-log: