spring:
  application:
    name: boutique
  datasource:
    url: jdbc:postgresql://localhost:3334/beautique
    username: beautique
    password: beautique
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        default_schema: beautique_schema
    hibernate:
      ddl-auto: update


server:
  servlet:
    context-path: /ms-beautique
  port: 8082
